"use client";

import { Trash2 } from "lucide-react";
import { useTranslations } from "next-intl";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { useToast } from "@/components/providers";

type Label = { id: string; name: string; color: string | null; sortOrder: number };
export function LabelsManager({ labels }: { labels: Label[] }) {
  const t = useTranslations("labels"); const common = useTranslations("common"); const notify = useToast(); const router = useRouter(); const [pending, setPending] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const form = new FormData(event.currentTarget); const response = await fetch("/api/labels", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), color: form.get("color"), sortOrder: Number(form.get("order")) }) }); notify(response.ok ? common("success") : common("error"), response.ok ? "success" : "error"); setPending(false); if (response.ok) { event.currentTarget.reset(); router.refresh(); } }
  async function update(event: FormEvent<HTMLFormElement>, id: string) { event.preventDefault(); setPending(true); const form = new FormData(event.currentTarget); const response = await fetch(`/api/labels/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), color: form.get("color"), sortOrder: Number(form.get("order")) }) }); notify(response.ok ? common("success") : common("error"), response.ok ? "success" : "error"); setPending(false); if (response.ok) router.refresh(); }
  async function remove(id: string) { if (!window.confirm(common("confirmDelete"))) return; const response = await fetch(`/api/labels/${id}`, { method: "DELETE" }); notify(response.ok ? common("success") : common("error"), response.ok ? "success" : "error"); if (response.ok) router.refresh(); }
  return <div><form className="card grid gap-4 p-5 sm:grid-cols-[1fr_9rem_7rem_auto] sm:items-end" onSubmit={submit}><div><label className="label" htmlFor="label-name">{t("name")}</label><input className="input" id="label-name" name="name" placeholder={t("mustWatch")} minLength={1} maxLength={40} required /></div><div><label className="label" htmlFor="label-color">{t("color")}</label><input className="input !p-1" id="label-color" name="color" type="color" defaultValue="#6f7654" /></div><div><label className="label" htmlFor="label-order">{t("order")}</label><input className="input" id="label-order" name="order" type="number" min="0" max="10000" defaultValue="0" /></div><button className="btn btn-primary" disabled={pending}>{t("create")}</button></form><div className="mt-5 grid gap-3">{labels.length ? labels.map((label) => <form className="card grid gap-3 p-4 sm:grid-cols-[1fr_8rem_7rem_auto_auto] sm:items-end" key={label.id} onSubmit={(event) => void update(event, label.id)}><div><label className="label" htmlFor={`label-name-${label.id}`}>{t("name")}</label><input className="input" id={`label-name-${label.id}`} name="name" defaultValue={label.name} minLength={1} maxLength={40} required /></div><div><label className="label" htmlFor={`label-color-${label.id}`}>{t("color")}</label><input className="input !p-1" id={`label-color-${label.id}`} name="color" type="color" defaultValue={label.color ?? "#6f7654"} /></div><div><label className="label" htmlFor={`label-order-${label.id}`}>{t("order")}</label><input className="input" id={`label-order-${label.id}`} name="order" type="number" min="0" max="10000" defaultValue={label.sortOrder} /></div><button className="btn btn-secondary" disabled={pending}>{common("save")}</button><button className="btn btn-danger !px-3" type="button" disabled={pending} onClick={() => void remove(label.id)}><Trash2 size={16} /><span className="sr-only">{common("delete")}</span></button></form>) : <p className="card muted p-6 text-center">{t("empty")}</p>}</div></div>;
}
