import { getLocale, getTranslations } from "next-intl/server";
import Image from "next/image";
import Link from "next/link";
import { formatWatchTime } from "@/lib/domain/time";
import { localizedTitle } from "@/lib/domain/title";
import type { getLibrary } from "@/server/services/library";
import type { getUserStats } from "@/server/services/stats";

export async function ProfileView({ profile, stats, library, preview = false }: {
  profile: { username: string; displayName: string | null; bio: string | null };
  stats: Awaited<ReturnType<typeof getUserStats>> | null;
  library: Awaited<ReturnType<typeof getLibrary>> | null;
  preview?: boolean;
}) {
  const t = await getTranslations("profile"); const dashboard = await getTranslations("dashboard"); const locale = (await getLocale()) as "pl" | "en";
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-8"><section className="card relative overflow-hidden p-6 sm:p-10"><div className="absolute inset-x-0 top-0 h-1 bg-[color:var(--accent)]" /><p className="muted text-sm">@{profile.username}</p><h1 className="mt-2 text-3xl font-black">{profile.displayName ?? profile.username}</h1>{profile.bio ? <p className="muted mt-4 max-w-2xl leading-7">{profile.bio}</p> : null}{preview ? <p className="muted mt-5 text-sm">{t("publicUrl")}: <Link className="accent" href={`/u/${profile.username}`}>/u/{profile.username}</Link></p> : null}</section>{stats ? <><section className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label={dashboard("totalTime")} value={formatWatchTime(stats.totalMinutes, locale)} /><Stat label={dashboard("movies")} value={stats.uniqueMovies} /><Stat label={dashboard("series")} value={stats.uniqueSeries} /><Stat label={dashboard("anime")} value={stats.uniqueAnime} /></section><section className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5"><Stat label={dashboard("fullMovieWatches")} value={stats.fullMovieWatches} /><Stat label={dashboard("cycles")} value={stats.completedSeriesCycles} /><Stat label={dashboard("rewatches")} value={stats.rewatches} /><Stat label={dashboard("seasons")} value={stats.watchedSeasons} /><Stat label={dashboard("episodes")} value={stats.approximateEpisodes} /></section><section className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-3"><Stat label={dashboard("moviesTime")} value={formatWatchTime(stats.timeByType.movies, locale)} /><Stat label={dashboard("seriesTime")} value={formatWatchTime(stats.timeByType.series, locale)} /><Stat label={dashboard("animeTime")} value={formatWatchTime(stats.timeByType.anime, locale)} /></section><section className="mt-6 grid gap-6 md:grid-cols-2"><Rank title={t("topGenres")} items={stats.genresByTime} locale={locale} /><Rank title={t("topMedia")} items={stats.mostWatched} locale={locale} /></section></> : <p className="card muted mt-6 p-6">{t("statsHidden")}</p>}{library ? <section className="mt-6"><h2 className="text-xl font-bold">{t("library")}</h2><div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-4 lg:grid-cols-6">{library.slice(0, 18).map((entry) => <article className="card overflow-hidden" key={entry.id}><div className="relative aspect-[2/3] bg-[color:var(--surface-raised)]">{entry.media.posterUrl ? <Image src={entry.media.posterUrl} alt="" fill sizes="160px" className="object-cover" /> : null}</div><p className="line-clamp-2 p-3 text-sm font-bold">{localizedTitle(entry.media, locale)}</p></article>)}</div></section> : <p className="card muted mt-6 p-6">{t("libraryHidden")}</p>}</main>;
}

function Stat({ label, value }: { label: string; value: string | number }) { return <article className="card p-4"><p className="muted text-xs">{label}</p><p className="mt-2 text-xl font-black">{value}</p></article>; }
function Rank({ title, items, locale }: { title: string; items: Array<{ name: string; value: number }>; locale: "pl" | "en" }) { return <section className="card p-5"><h2 className="font-bold">{title}</h2><ol className="mt-4 grid gap-3">{items.map((item, index) => <li className="flex justify-between" key={item.name}><span><span className="muted mr-3">{index + 1}.</span>{item.name}</span><span className="muted text-sm">{formatWatchTime(item.value, locale)}</span></li>)}</ol></section>; }
